"""inicial

Revision ID: 502ddc1b6adc
Revises: 
Create Date: 2023-07-04 15:33:50.958406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502ddc1b6adc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
