"""adicionando relationships do sqlalchemy

Revision ID: 96120c032bd5
Revises: 4a1a81c3948a
Create Date: 2023-06-29 10:52:12.270437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96120c032bd5'
down_revision = '4a1a81c3948a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
