name: Continuous integration

on:
  workflow_dispatch:

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest

    - name: Update current version
      uses: fernandofukunaga/my-game-library-backend/update-version@v1

    - name: Build Docker image
      run: |
        docker build -t fernandofukunaga/my-game-library-backend@${{ env.CURRENT_VERSION }} .

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}        

    - name: Push image to DockerHub
      run: |
        docker push ${docker images -q}
