name: Test enviroment variable

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Exibir o valor da variável de ambiente
      run: echo ${{ vars.CURRENT_VERSION }}
